baseURL = 'https://acmeprotocol.dev/'
languageCode = 'en-us'
title = 'ACME and the WebPKI'
enableRobotsTXT = true

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true
# Don't display 'Last Modified by' date and git author information on 'doc' type pages.
enableGitInfo = false
# The https://themes.gohugo.io/themes/hugo-book/ theme doesn't render taxonomy,
# so let's remove related files.
disableKinds = ['taxonomy']

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
# Switch between dark and light modes based on browser/os preferences.
BookTheme = 'auto'
# Display ToC  on the right side of pages. Can be disabled per-page in the front matter.
BookToC = true
# Render all sections into the menu.
BookSection = '*'
# Disable search functions.
BookSearch = false
# Disable comments posting.
BookComments = false

[markup]
[markup.goldmark.renderer]
# Goldmark trims unsafe outputs which prevent https://hugo-book-demo.netlify.app/docs/shortcodes/hints/
# shortcodes from rendering. Thus, it must be set to unsafe mode.
unsafe = true
[markup.tableOfContents]
startLevel = 1

[menu]
[[menu.after]]
name = "Contribute to this Website"
url = "https://github.com/fhchstr/acmeprotocol.dev"
weight = 10

[services]
[services.googleAnalytics]
id = 'G-0LW86NH9LL' # https://analytics.google.com/

[privacy]
[privacy.googleAnalytics]
disable = false
respectDoNotTrack = true
